AllCops:
  NewCops: enable
Metrics/BlockLength:
  Max: 600
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/LineLength:
  Max: 140
require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec